### PR TITLE
[Announce] Altered tests to make time consistent with patching

### PR DESCRIPTION
**Pull request by Copper76**

### CODE REVIEW

**Comment by JayDwee** [comment]
Worth using patching instead so you don't have to add '+- x secs'

**Comment by Copper76** [comment]
That is what I was asking Viraj last time, what do you mean by patching here

**Comment by JayDwee** [comment]
> That is what I was asking Viraj last time, what do you mean by patching here
@Copper76 
Apologies, I meant mocking, Take a look at @mock.patch as used in `test_TwitchAlert.py` (e.g. `test_edit_default_message_default_from_none()`)

**Review by JayDwee — APPROVED** [review]
👍

**Pull request merged**
